name: tabular
description: Dart library for easily displaying tabular data in a visually appealing ASCII table format.
version: 0.2.2-alpha
repository: https://github.com/rtmigo/tabular

environment:
  sdk: ">=2.12.0 <3.0.0"
  #//sdk: '>=2.10.0 <3.0.0'

dependencies:
  quiver: ^3.0.0
  # none

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
