name: tabular
description: Dart library for displaying tabular data in a visually appealing ASCII table format.
version: 0.6.1
repository: https://github.com/rtmigo/tabular_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  quiver: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
